### ISSUE TITLE
Versions are not synced

### ISSUE THREAD

**Issue by stabldev** [sirilmp/validate-express-req-body#12]
hi, just noticed `package.json` version and `npm` version seems not synced.
> `1.3.4` !== `1.5.0`

https://github.com/sirilmp/validate-express-req-body/blob/027917b4ba3ed54249fd7c4319daa13afb576494/package.json#L3

i'd suggest [changesets](https://github.com/changesets/changesets) over `semantic-releases` to handling everything smoothly (changelog(s), versions syncing, github releases....)
its just me opinion, see what you're comfortable with.

**Comment by sirilmp** [comment]
fixed
