### ISSUE TITLE
Feat: Some suggestions

### ISSUE THREAD

**Issue by stabldev** [sirilmp/validate-express-req-body#5]
Hi there,
saw this project on telegram group, just leaving some of me suggestions here.

 - you could use a CI/CD pipline for build/testing
 - take a look at [changesets](https://github.com/changesets/changesets) for managing releases
 - or, handle github releases manually

edit:
 - try to follow [semantic versioning](https://semver.org/)

thats it for now,
good luck with project :D

**Comment by sirilmp** [comment]
Hi @moonlitgrace,

Thank you so much for your feedback and suggestions!

I’m working on integrating a CI/CD pipeline and exploring changesets for release management. Your points on semantic versioning are also well-noted and appreciated.

I’d love to collaborate further on this project if you’re interested. Feel free to reach out if you have more ideas or would like to contribute!

Thanks again for your support

**Comment by stabldev** [comment]
> Hi @moonlitgrace,
> 
> Thank you so much for your feedback and suggestions!
> 
> I’m working on integrating a CI/CD pipeline and exploring changesets for release management. Your points on semantic versioning are also well-noted and appreciated.
> 
> I’d love to collaborate further on this project if you’re interested. Feel free to reach out if you have more ideas or would like to contribute!
> 
> Thanks again for your support

you are most welcome, thing is i dont use expressjs so dunno what to improve or any project related suggestions :)
so yea feel free to close this anytime.

**Comment by sirilmp** [comment]
1. CI/CD Pipeline Setup:
I have configured a CI/CD pipeline specifically for the develop branch. This pipeline handles the build and testing processes to ensure code quality and functionality before merging changes.

2. Use of Semantic Release:
For managing releases, I am using Semantic Release. This tool automates the versioning and publishing process based on the changes made to the code, ensuring that version numbers and release notes are generated consistently and accurately.

3. GitHub Releases:
Currently, the release management is handled by Semantic Release, which integrates with GitHub to publish releases automatically. This approach minimizes manual intervention and helps maintain an organized release history.
